"""application tables

Revision ID: 39ca0af83305
Revises: f9c93dc1cc43
Create Date: 2024-07-14 18:52:57.630755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39ca0af83305'
down_revision = 'f9c93dc1cc43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('longname', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('longname'),
    sa.UniqueConstraint('name')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accountability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ws_id', sa.Integer(), nullable=True),
    sa.Column('wh_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['wh_id'], ['warehouse.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ws_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=50),
               nullable=False)
        batch_op.drop_column('direction')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint('item_ibfk_1', type_='foreignkey')
        batch_op.drop_column('commodity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commodity_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('item_ibfk_1', 'commodity', ['commodity_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', mysql.VARCHAR(collation='utf8mb3_bin', length=3), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=50),
               nullable=True)

    op.drop_table('accountability')
    op.drop_table('warehouse')
    op.drop_table('province')
    op.drop_table('branch')
    op.drop_table('region')
    op.drop_table('document')
    # ### end Alembic commands ###
